FROM letta/letta:latest
RUN /app/.venv/bin/python3 -m ensurepip && \
    /app/.venv/bin/python3 -m pip install mem0ai && \
    /app/.venv/bin/python3 -m pip install 'protobuf<6.0' && \
    /app/.venv/bin/python3 -m pip install fastembed && \
    /app/.venv/bin/python3 -m pip install 'mem0ai[nlp]'